#!/usr/bin/env sh

avr-gcc -mmcu=atmega328p -c main.c -o main.o || exit 1
avr-gcc -mmcu=atmega328p main.o -o main.elf || exit 1
avr-objcopy -O ihex -R .eeprom main.elf main.hex || exit 1
avrdude -c arduino -p m328p -P /dev/ttyUSB0 -b 115200 -U flash:w:main.hex

# arduino-cli compile --fqbn arduino:avr:uno arduino.c
# arduino-cli upload -p /dev/ttyUSB0 --fqbn arduino:avr:uno arduino.ino
